### ISSUE TITLE
Pretty printer

### ISSUE THREAD

**Issue by nofun97** [arr-ai/arrai#171]
### Tasks
1. [ ] Add a pretty print function to arrai itself. `//fmt.pretty(config, value)`

2. [ ] Using `$"..."` instead of regular string to show indentations and newlines.
For example, currently the output `//net.http.get` uses regular strings, which can return strings such as `"random\nstring"`. The use of `$"..."` can show the indentations.
```
(
  body: $"
    all: test lint wasm
    # TODO: If this Makefile is ever used for CI, suppress timingsensitive there.
    test:
    	go test $(GOTESTFLAGS) -tags timingsensitive ./...
    lint:
    	golangci-lint run
    wasm:
    	GOOS=js GOARCH=wasm go build -o /tmp/arrai.wasm ./cmd/arrai",
  header:(
...
```

3. [ ] Pretty print tuple
```
  header:(
    'Accept-Ranges':               ['bytes'],
    'Access-Control-Allow-Origin': ['*'],
    'Cache-Control':               ['max-age=300'],
    'Connection':                  ['keep-alive'],
    'Content-Security-Policy':     ["default-src 'none'; style-src 'unsafe-inline'; sandbox"],
    'Content-Type':                ['text/plain; charset=utf-8'],
    'Date':                        ['Mon, 13 Apr 2020 12:17:00 GMT'],
    'Etag':                        ['W/"d7460fe5d998b2f25ba976ca6ef6646215c0b3314608fb5462a48f6412334f13"'],
    'Expires':                     ['Mon, 13 Apr 2020 12:22:00 GMT'],
    'Source-Age':                  ['246'],
    'Strict-Transport-Security':   ['max-age=31536000'],
    'Vary':                        ['Authorization,Accept-Encoding'],
    'Via':                         ['1.1 varnish (Varnish/6.0)', '1.1 varnish'],
    'X-Cache':                     ['MISS, HIT'],
    'X-Cache-Hits':                ['0, 1'],
    'X-Content-Type-Options':      ['nosniff'],
    'X-Fastly-Request-Id':         ['fe13435de8287048b85b80e6057b941d3470dea6'],
    'X-Frame-Options':             ['deny'],
    'X-Github-Request-Id':         ['8956:2496:13C90C:1631AA:5E945745'],
    'X-Served-By':                 ['cache-mel19034-MEL'],
    'X-Timer':                     ['S1586780220.448718,VS0,VE1'],
    'X-Xss-Protection':            ['1; mode=block']
  )
```

**Comment by orlade-anz** [comment]
It would be great if the repl could pretty print all output if some kind of `ARRAI_PRETTY` env var was set.

**Comment by ericzhang6222** [comment]
> It would be great if the repl could pretty print all output if some kind of `ARRAI_PRETTY` env var was set.

@orlade-anz, it is a flag to do pretty print or a pattern how to parse string or something else?

**Comment by ericzhang6222** [comment]
In my mind the right approach is building a string parser which can parse string and format to add indents etc. I analyzed and find it can't be done quickly.
And now `//fmt.pretty(tuple)` or `//fmt.pretty(dict)` can help team most, and this one can be done by walking through `tuple` and `dict` data quickly.
So I will do `//fmt.pretty` first with walking through `tuple` and `dict` data.

**Comment by ericzhang6222** [comment]
Pending items:
https://github.com/arr-ai/arrai/pull/511#pullrequestreview-451343605
https://github.com/arr-ai/arrai/pull/511#issuecomment-660847765

**Comment by ericzhang6222** [comment]
https://anzx.slack.com/archives/C0130J1UUKT/p1595376169450400?thread_ts=1595326485.449000&cid=C0130J1UUKT

Updates:
`//fmt.pretty()` should simply return a string containing the formatted output. Having it as an arr.ai function isn't a priority, imo. It would rather have it integrated into the output stage of `arrai run/eval/shell` and `//log.print`.

**Comment by marcelocantos** [comment]
> It would be great if the repl could pretty print all output if some kind of `ARRAI_PRETTY` env var was set.

If it's done well enough, we should just make it the default. Forcing output onto a single line might be desirable in some cases, so it could be made available through some opt-in mechanism.

**Comment by Allon-Guralnek** [comment]
Bug: `//fmt.pretty()` outputs `()` instead of the prettier `true`.
